# @package _global_
defaults:
  - end_to_end_defaults
  - env_config/lean4_env
  - tac_model/diversity_internlm
  - search_model/bestfs

exp_config:
  name: 3dprover_internlm_k8
  experiment: internlm_dpp


logging_config:
  project: internlm_dpp
  offline: false


