# @package _global_
defaults:
  - end_to_end_defaults
  - env_config/lean4_env
  - tac_model/topk_internlm
  - search_model/bestfs

exp_config:
  name: bestfs_topk_8
  experiment: internlm_dpp

logging_config:
  project: internlm_dpp
  offline: false


