env: leandojo
#data_path: data/LeanDojo/data/leandojo_minif2f/default/
data_path: data/LeanDojo/data/lean4_minif2f/default/
#data_path: data/LeanDojo/data/leandojo_benchmark_4/novel_premises/
split: test
file_path: null
full_name: null
name_filter: null
num_theorems: 245

name: null
indexed_corpus_path: null
