# @package _global_
defaults:
  - /base/logging_config@_here_
  - /base/exp_config@_here_

exp_config:
  name: autoencoder
  experiment: diversity

logging_config:
  project: diversity
  offline: false

model:
  _target_: models.end_to_end.tactic_models.tac_embed_autoencoder.model.AutoEncoderTacModel
  config:
    tac_model: pretrained_tactic_generator_path
    decoder: pretrained_tactic_generator_path
    max_length: 2300
    num_samples: 8
    lr: 5e-5
    warmup_steps: 200

data_module:
  _target_: models.end_to_end.tactic_models.tac_embed_autoencoder.datamodule.AutoEncoderDataModule
  model_name: pretrained_tactic_generator_path
  batch_size: 8 # effective_batch_size == batch_size * accumulate_grad_batches * devices
  eval_batch_size: 8
  max_seq_len: 2300
  num_workers: 0
  collection: minif2f_autoenc
  trace_files: 'trace_dir' # add path to the trace files for the desired proof attempt
  replace: 'keep' # add/keep/drop files wrt the existing collection


trainer:
  accelerator: gpu
  devices: 2
#  num_nodes: 2
  precision: bf16-mixed
  strategy:
    _target_: lightning.pytorch.strategies.DeepSpeedStrategy
    stage: 2
    offload_optimizer: false
    cpu_checkpointing: false
    logging_batch_size_per_gpu: 8

  gradient_clip_val: 1.0

  val_check_interval: 10_000
  limit_val_batches: 10_000

  callbacks:
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: step
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      verbose: true
      save_top_k: 3
      save_last: true
      monitor: val_bleu
      mode: max
      dirpath: ${exp_config.directory}/checkpoints
      auto_insert_metric_name: true
      filename: "{epoch}-{step}-{max:.2f}"
      enable_version_counter: false
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: val_bleu
      patience: 10
      mode: max
      verbose: true
