env: leandojo
data_path: data/LeanDojo/data/leandojo_benchmark/novel_premises/
split: test
file_path: null
full_name: null
name_filter: null
num_theorems: 2000 #244

name: null
indexed_corpus_path: null
