# @package _global_
defaults:
  - end_to_end_defaults
  - env_config/leandojo_minif2f_test
  - tac_model/topk
  - search_model/bestfs

exp_config:
  name: bestfs_topk
  experiment: minif2f_test

logging_config:
  project: minif2f_test
  offline: false


