program: experiments.end_to_end.end_to_end_experiment
name: Ablation
description: Ablation for miniF2F-valid
project: minif2f

method: grid
metric:
  goal: maximize
  name: Pass@1
parameters:
  tac_model.diversity_config.score_network:
    values: [ true ]
  tac_model.diversity_config.fixed_size:
    values: [ true ]
  tac_model.diversity_config.num_filtered:
    values: [ 32, 16, 8 ]
  tac_model.diversity_config.error_weight:
    values: [ 0.0, 0.1, 0.5 ]
  tac_model.diversity_config.time_weight:
    values: [ 0.0, 0.1, 1.0 ]
  tac_model.diversity_config.temperature:
    values: [ 1, 4 ]
  exp_config.name:
    values: [ 'ablation-k${tac_model.diversity_config.num_filtered}' ]

command:
  - ${env}
  - ${interpreter}
  - '-m'
  - ${program}
  - '--config-name=end_to_end/3d_prover'
  - ${args_no_hyphens}

